api_platform:
  mapping:
    paths: ['%kernel.project_dir%/src/Entity']
  formats:
    jsonld:   ['application/ld+json']
    jsonhal:  ['application/hal+json']
    jsonapi:  ['application/vnd.api+json']
    json:     ['application/json']
    xml:      ['application/xml', 'text/xml']
    yaml:     ['application/x-yaml']
    csv:      ['text/csv']
    html:     ['text/html']
  collection:
    pagination:
      page_parameter_name: _page
      enabled: false
      client_enabled: true
      enabled_parameter_name: pagination # optional
      client_items_per_page: true # Disabled by default
      items_per_page_parameter_name: itemsPerPage # Default value
      items_per_page: 100 # Default value
      maximum_items_per_page: 500
      partial: false # Disabled by default
      client_partial: true # Disabled by default
      partial_parameter_name: 'partial' # Default value